name: Build APK

on:
  push:
    branches:
      - ci/cd
  pull_request:
    branches:
      - ci/cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Install dependencies
        run: |
          npm install
          cd android
          gradle wrapper
          chmod +x ./gradlew
          ./gradlew clean

      - name: Build APK
        run: |
          cd android
          ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
