name: Lint

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Lint
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JS: true
          VALIDATE_JSX: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
